### ISSUE TITLE
Readme / setup improvements

### ISSUE THREAD

**Issue by randallmlough** [t-lock/sveltempl#3]
Heads up - I had issues getting this project to run beyond the `README.md` instructions.

My first issue is this project was complaining about `rollup.js` not being installed and since I didnt see it in the dependencies list, I had to manually add it as a dev dependency. 

My next issue was with tailwind cli. Is there a reason you specifically wanted the standalone install? For me it worked better to use `npx tailwindcss ...` over installing the standalone cli. 

I added a PR (#2) with my changes. Feel free to reject or change as you see fit

This is a cool PoC though! Looking forward to diving deeper

**Comment by t-lock** [comment]
Hi @randallmlough thanks for your interest in the project!

Re rollup: this should be bundled with Vite, and I can see it in my node_modules when I wipe and do a clean npm install, so that is strange indeed. Do you mind trying a fresh install again?

Re tailwind: when bootstrapping this repo I used https://github.com/Melkeydev/go-blueprint which is go-focused so doesn't assume users have/want js-based tooling, but I agree with you npx would be simpler (and node is in the stated reqs).

**Comment by randallmlough** [comment]
@t-lock - yeah strange. I wonder it was a residual artifact from the last previous [commit removing rollup](https://github.com/t-lock/sveltempl/commit/ee78640f921964e49dc6ddbe9aefc73877dc5b01#diff-d8449bab9184dab82c559421b12e1bc507e9efbab2240cfff3bc9aefb2affb25). I can't reproduce anymore myself even after a fresh clone of the repo. 

I removed installing rollup in the PR and just left installing tailwind via npx over standalone.

Thanks for your quick reply

**Comment by t-lock** [comment]
Merged!
