### ISSUE TITLE
Could Inertia.js be a viable option?

### ISSUE THREAD

**Issue by randallmlough** [t-lock/sveltempl#5]
I'm not sure if you are already familiar with [inertia.js](https://inertiajs.com/), but I just learned about it and it seems interesting. There's already a couple [go ports available](https://inertiajs.com/community-adapters) too. 

I have no idea if this would be well suited for this project, but I figured I'd pass it along just in case. I was wondering/thinking it could replace the need for gov8

**Comment by t-lock** [comment]
Inertia doesn't server-render the initial view of the JS component as html/css. It prints your data to the html page from whatever server-side language in a format that the javascript library knows how to ingest, uses that data to mount js component tree, and then adds some client routing on top. It creates a traditional client-side rendered SPA (entire page as opposed to islands, and no ssr), but cuts out the REST API that typically goes between server and client. See: https://inertiajs.com/how-it-works

As such, while it does overlap a portion of what Sveltempl does (data transfer embedded in html response) they are not compatible or aligned in their goals. Sveltempl produces fully server-rendered pages which get automatically hydrated on load, and it operates as "islands of interactivity", you don't need to write the entire UI in JS. Although, technically you could do that if you just wanted a fully SSR'ed version of inertia, your entire page could be a single Sveltempl component. As for client-routing, we can achieve it by using HTMX with the `hx-boost` attribute, as is demonstrated on the demo site's main navigation. HTMX automatically executes inline scripts when it loads partial html responses, and that's all we need since every Sveltempl html component has its own initialization script and prop data contained within as an inline es module script tag and a json script tag.

Check out the differences between the html responses from Inertia's and Sveltempl's demo sites:
view-source:https://demo.inertiajs.com/login
view-source:https://sveltempl.tlock.dev/trello-clone

It is interesting though to be sure. Actually, when I first heard about Inertia, I thought it was what I had been dreaming of. Realizing that it didn't in fact do any SSR / handoff of rendered html is part of the journey that brought me to experiment with embedding v8 and writing Sveltempl. 

One of the things on my list of todos blocking a v0.1.0 release is to write up a decent "how it works" page. The closest thing to that right now is inspecting the page source. I haven't looked super closely at how Inertia handles its "data handoff", but I _love_ the way that Sveltempl does it. It is very elegant, and the lessons learned here can be more or less language agnostic. More on that someday as well, there are big plans, but I have a 2 year old, a newborn due in a couple weeks, a job, and just got side-tracked writing a [GUI screenshot utility in Go](https://github.com/t-lock/golang-gui-screenshot-util) 😁

**Comment by t-lock** [comment]
> the lessons learned here can be more or less language agnostic. More on that someday as well, there are big plans

And by that I mean that there is no reason that the core architecture here can't achieve all of the following:
![cropped](https://github.com/user-attachments/assets/7f971d7b-5149-42f6-9324-3cf462157bae)
